### ISSUE TITLE
[recette finale] on peut saisir n'imp dans le champs des salaires

### ISSUE THREAD

**Issue by omansour** [afup/barometre#101]
http://localhost:8000/app_dev.php/report/company_size?filter%5Bsalary%5D%5Bmin%5D=eraa&filter%5Bsalary%5D%5Bmax%5D=eaeae

![distribution_des_tailles_d_entreprises___baromtre_afup](https://f.cloud.github.com/assets/1131098/2309489/3c9bb8ea-a2d4-11e3-8c39-1d1c34ddec68.jpg)

bon après le filtrage semble l'ignorer

**Comment by agallou** [comment]
ajouter des contraintes dans le buildForm sur https://github.com/agallou/barometre/blob/1de6446bba07373d2abb102d52303c02cac2bc6f/src/Afup/Barometre/Filter/SalaryFilter.php#L18

**Comment by klnjmm** [comment]
@agallou Quel est le comportement voulu ?
Actuellement, les champs min et max du filtre sur les salaires sont les seuls champs de texte "libre" (les autres champs sont des listes de sélection).
Lorsque la valeur n'est pas dans le bon format, cela n'est pas pris en compte.
Plusieurs possibilités : 

1. On laisse comme c'est là. Juste une petite correction à faire quand l'un des deux champs n'est pas renseigné (dans l'image, seul le min est renseigné)
![image](https://user-images.githubusercontent.com/15214050/36377288-e876fa1c-1576-11e8-8749-2ea42cc6b50f.png)

2. On peut passer ces deux inputs en type `number`, ce qui permettrait suivant les navigateurs de faire une validation HTML 5.

3. Affichage d'un message d'erreur une fois le formulaire validée en affichant le résultat sans prendre en compte ce filtrage. Comme pour les années par exemple quand on modifie l'id d'un choix de la liste
![image](https://user-images.githubusercontent.com/15214050/36377419-646c72b4-1577-11e8-87f6-992fefc76e62.png)
 => je ne trouve pas cela très élégant comme affichage.

Personnellement, je serais pour possibilités 1+2

**Comment by agallou** [comment]
Effectivement les possibilités 1+2 corrigeront la plupart des cas.
Ça n’empêche pas de faire la troisième, pour plus contrôles, mais on pourra faire celle-ci dans un second temps.
