### ISSUE TITLE
salaires présentés tiennent ils compte du variable ? 

### ISSUE THREAD

**Issue by omansour** [afup/barometre#157]
http://barometre.afup.org/report/salary?filter[campaign][]=4&filter[departement][]=75&filter[departement][]=77&filter[departement][]=78&filter[departement][]=91&filter[departement][]=92&filter[departement][]=93&filter[departement][]=94&filter[departement][]=95&filter[salary][min]=&filter[salary][max]=&filter[specialities][]=19&filter[submit]=

ne faudrait il pas ajouter un autre rapport pour présenter le variable ou le fixe + le variable ?

**Comment by omansour** [comment]
ping @agallou ?

**Comment by BenoitLeveque** [comment]
alors ce report ne tient pas compte du variable, on prend uniquement le salaire fix

**Comment by klnjmm** [comment]
Je me permets de demander si cette issue qui date de 2014 a toujours raison d'être ?
