### ISSUE TITLE
fix blank line in status distribution report 

### ISSUE THREAD

**Issue by omansour** [afup/barometre#166]
cf https://github.com/afup/barometre/pull/162 

![distribution_des_statuts___barometre_afup](https://cloud.githubusercontent.com/assets/1131098/5564753/a4507918-8ed2-11e4-81ef-6b22aaef1f45.jpg)

http://barometre.afup.org/report/status?filter[campaign][0]=4

**Comment by Guillaume-Rossignol** [comment]
Apparement, celui là a déjà été corrigé. En tout cas, depuis mon navigateur, je n'ai pas le bug

**Comment by omansour** [comment]
yes :)
