### ISSUE TITLE
ajouter un bandeau "fork me on github" sur le site

### ISSUE THREAD

**Issue by omansour** [afup/barometre#168]
pour mettre en avant que le code est open source ?

**Comment by agallou** [comment]
Voici plusieurs versions. On partirait plutôt sur laquelle ?

Version 1:
![capture d ecran 2015-02-04 a 00 04 08](https://cloud.githubusercontent.com/assets/320372/6031645/615ad080-ac01-11e4-8cd1-6496ab288aff.png)

Version 2 :
![capture d ecran 2015-02-04 a 00 03 05](https://cloud.githubusercontent.com/assets/320372/6031646/615db17e-ac01-11e4-97ff-7a540c0426ac.png)

Version 3 :
![capture d ecran 2015-02-04 a 00 01 07](https://cloud.githubusercontent.com/assets/320372/6031647/6160fb4a-ac01-11e4-9781-7207f1f5865a.png)

**Comment by omansour** [comment]
v2, agence-e ne participe plus au baromètre. 

mais le noir ça fait pas un peu deuil ? :)

**Comment by benji07** [comment]
sinon on prend le bleu ? https://github.com/petethepig/github-ribbons-css
