### ISSUE TITLE
faire un listing des retombées presse

### ISSUE THREAD

**Issue by omansour** [afup/barometre#170]

**Comment by omansour** [comment]
http://www.journaldunet.com/developpeur/php/salaire-du-developpeur-php
http://pro.clubic.com/emploi-informatique.clubic.com/actualite-602350-developpeur-php-salaire-metier-perspective-satisfaction-etude-afup.html
http://pro.clubic.com/emploi-informatique.clubic.com/actualite-739143-afup-barometre-php-salaire-developpeur-secteur.html
http://www.programmez.com/actualites/le-salaire-des-developpeurs-php-en-france-21598

**Comment by agallou** [comment]
@omansour quelquechose comme ça ?
![screen shot 2016-10-08 at 13 19 55](https://cloud.githubusercontent.com/assets/320372/19213105/a5a416c2-8d62-11e6-9c60-ccc122867f32.png)

**Comment by benji07** [comment]
👍

**Comment by omansour** [comment]
excellent ! merci
