### ISSUE TITLE
pb dans la répartition des salaires par spécialité sur 2014

### ISSUE THREAD

**Issue by omansour** [afup/barometre#172]
http://barometre.afup.org/report/speciality_salary?filter%5Bcampaign%5D%5B%5D=4&filter%5Bsalary%5D%5Bmin%5D=&filter%5Bsalary%5D%5Bmax%5D=&filter%5Bsubmit%5D= 

![repartition_du_salaire_par_specialite___barometre_afup](https://cloud.githubusercontent.com/assets/1131098/5989114/afb91048-a97c-11e4-96b1-5df2ad35ee2c.jpg)

le rapport de 2013 est correct

c 'est peut être un soucis dans les données ????

**Comment by Guillaume-Rossignol** [comment]
Peut-être une prise de conscience globale sur l'utilisation d'outils propriétaire ? 

Plus sérieusement les lignes 166-177 de ResponseFactory : 
̀```
#!php
<?php
protected function addSpeciality(Response $response, array $specialityList)
    {
        foreach ($specialityList as $speciality) {
            $speciality = $this->specialityRepository->findOneBy(array('name' => trim($speciality)));

            if (!$speciality instanceof Speciality) {
                continue;
            }

            $response->addSpeciality($speciality);
        }
    }
```
me font imaginer un probléme d'encodage et de conversion entre le format du CSV importé et la config symfony/serveur.

Ceci dit, ca explique pas pourquoi la campagne 2013 s'est bien importée. Il y a eu un changement du nom "framework propriétaire" entre temps, un changement de machines ?

**Comment by omansour** [comment]
grumf, il faudrait avoir accès aux données de prod pour creuser ça 

@BenoitLeveque @agallou vous avez une idée ?

**Comment by omansour** [comment]
Les données de prod indique 28 réponses "frameworks propriétaires" 
![afup_org___localhost___barometre___response_speciality___phpmyadmin_4_1_14](https://cloud.githubusercontent.com/assets/1131098/6087630/43d2c262-ae4e-11e4-9eed-868c5bd48ebb.jpg)


je pense qu'il y a un bug dans ce rapport : https://github.com/afup/barometre/blob/master/src/Afup/Barometre/Report/SpecialitySalaryReport.php

**Comment by Guillaume-Rossignol** [comment]
Hum... le bug qui va être tres, tres drole. Il n'est pas présent avec les fixtures fournies de base.

![Uploading barometre1.png . . .]()

Mais sans vouloir être pessimiste, j'imagine un probleme plus "grave" que juste sur le framework proprietaire, parce que si je prend la repartition géographique avec la spécialité symfony j'arrive difficile à 300 reponses. http://barometre.afup.org/report/company_department?filter[campaign][]=4&filter[salary][min]=&filter[salary][max]=&filter[specialities][]=19&filter[submit]=

Et toujours en repartition géo, en additionnant tous les resultat à la main, j'arrive à 1460, c'est moins que juste zend et symfony sur le tableau du haut. Je vais essayer de mettre le bazar dans la BDD de mon coté pour essayer de reproduire.

**Comment by omansour** [comment]
je pense que c'est du au fait qu'on peut choisir plusieurs spécialités. tu ne peux pas les compter simplement 

de plus les chiffres que j'ai données plus haut sont 2013+2014 soit : http://barometre.afup.org/report/company_department?filter%5Bcampaign%5D%5B%5D=3&filter%5Bcampaign%5D%5B%5D=4&filter%5Bsalary%5D%5Bmin%5D=&filter%5Bsalary%5D%5Bmax%5D=&filter%5Bsubmit%5D=

**Comment by Guillaume-Rossignol** [comment]
Bon, je bloque sur la reproductibilité du bug sur ma machine.

Mettons de coté la question de la pertinence du rapport de la répartition des salaires par spécialité. De toutes facons, on ne peut pas filtrer sur la valeur framework propriétaire sur le site de prod (12 résultat pour 2013, aucun pour 2014 (le rapport sur le salaire moyen par sexe est tres pratique pour le coup)).

La valeur Framework propiétaire serait codé deux fois en table, on l'aurait deux fois dans les filtres, donc de ce coté là, on est tranquille. 

On ne peut pas avoir de campagne avec un nom `null` et une campagne avec un nom vide apparait dans les choix possible, donc sauf si les tables ne sont pas intégre en prod, ce n'est pas ça non plus.

Le code SQL à la sortie du filtre `SpecialityFilter` est assez classique (j'ai adapté les ids aux valeurs en prod): 
```
#!sql
SELECT response.id as response_id FROM response response INNER JOIN response_speciality response_speciality ON response.id = response_speciality.response_id INNER JOIN speciality speciality ON response_speciality.speciality_id = speciality.id WHERE (response.campaign_id IN (4)) AND (speciality.id IN (27)) GROUP BY response_id
```

Normalement, on devrait avoir 14 réponses (28 framework pro dont 12 en 2013)

Si on ne les a pas, la commande ci dessous devrait permettre de débusquer les 14 réponses cachée et pouvoir deviner quel est le souci. 
```
SELECT response.* FROM response response INNER JOIN response_speciality response_speciality ON response.id = response_speciality.response_id WHERE response_speciality.speciality_id=27
```

Donc je suis preneur de toute info qui permettrait de reproduire le souci en local, pour l'instant, je me casse les dents là-dessus. Je vais aller jouer avec #102 ca va être plus reposant :)

**Comment by omansour** [comment]
@Guillaume-Rossignol je pense qu'en fait il n'y a pas de bug. c'est simplement que le rapport n'était pas pertinent. cf https://github.com/afup/barometre/pull/189 

il n'y a aucune réponse "Framework propriétaire" en 2014 surement à cause d'un pb dans le formulaire 

j'attend de voir ce que cela donne en prod mais je pense que le ticket va être fermé

**Comment by omansour** [comment]
le pb est résolu en prod suite à la dernière mep. 

il reste un soucis sur la restitution du tableau 

![banners_and_alerts_and_repartition_du_salaire_par_specialite___barometre_afup_and_predis_reconnect_on_error_-_recherche_google](https://cloud.githubusercontent.com/assets/1131098/6263383/239d1ff6-b817-11e4-996f-56f4d75c47e8.jpg)

**Comment by BenoitLeveque** [comment]
il y avais un problème dans les données de 2014, une ligne ne contenait pas d'information sur l'expérience, j'ai mis à jour cette donnée dans la base, je vais faire une PR pour que si l'on ré-importe 2014 on n'est plus ce genre de problème
