### ISSUE TITLE
filtrage sur les alpes maritime 

### ISSUE THREAD

**Issue by omansour** [afup/barometre#174]
le filtrage sur les alpes maritime m'indique qu'il y a trop peu de données : http://barometre.afup.org/report/salary?filter%5Bcampaign%5D%5B%5D=4&filter%5Bdepartement%5D%5B%5D=06&filter%5Bsalary%5D%5Bmin%5D=&filter%5Bsalary%5D%5Bmax%5D=&filter%5Bsubmit%5D= 

toutefois la répartition géographique m'indique 42 réponses ... comment est ce possible ? :)

![repartition_geographique___barometre_afup](https://cloud.githubusercontent.com/assets/1131098/5989161/361e4558-a97e-11e4-9087-a62e3d389804.jpg)

**Comment by Guillaume-Rossignol** [comment]
Etrangement, le survol du département dans la carte me donne bien Alpes Maritimes / 0
![test](https://cloud.githubusercontent.com/assets/7794372/5992268/11cf7c54-aa22-11e4-9917-58f420381e26.png)

**Comment by Guillaume-Rossignol** [comment]
Je n'ai pas accés aux données 2014, ceci dit j'ai reproduit le bug avec les données de tests avec un `update response set companyDepartment="3" where companyDepartment="03";`.  Je suis encore en train de "rentrer dans le code" mais : 
* le bundle "agallou/departements" fait une correspondance "XX" => departement
* La methode getLabel est appelé avec un argument qui permet de completer lorsqu'on n'a pas mis le 0 sur les département à un chiffre
* On ne peut pas setter le filtre avec une valeur qui n'est pas une 'vraie' valeur (c'est à dire qu'on l'appel forcement avec la valeur 06)
* Le code du departement est forcement un varchar(3) en raison notamment de la corse.

Tout ca réuni fait qu'on ne peut pas chercher les résultat en departement 6 mais qu'il n'y a pas de résultat pour le département 06 puisque c'est stocké en département 6

Du coup, je ne sais pas si la correction du bug doit faire en sorte 
* qu'on ne puisse pas faire d'import/d'ajout d'une réponse avec un département à un chiffre (sachant que du coup, il faudra rectifier "à la main" la base existante
* que le filtre corrige les valeurs à 1 caractere. Par contre, j'ai peur que ça complexifie la clause `group BY` lorsqu'on obtient les résultat globaux.

Je vais m'orienter vers la premiere solution ce soir, mais je veux bien vos avis.

**Comment by BenoitLeveque** [comment]
après avoir passer le patch sql le filtrage et la carte fonctionne

**Comment by omansour** [comment]
top ! merci à tous
