### ISSUE TITLE
Cohérence version php requise

### ISSUE THREAD

**Issue by Guillaume-Rossignol** [afup/barometre#180]
Dans le composer.json il est indiqué `"php": ">=5.3.3"` mais j'ai croisé des notations courtes de tableaux qui sont disponibles depuis la 5.4

**Comment by omansour** [comment]
on peut target 5.5 je pense. C'est la prod

**Comment by BenoitLeveque** [comment]
oui, on n'a pas pris le temps de mettre à jour le composer.json, mais oui on peut mettre 5.5
