### ISSUE TITLE
Le menu de la version mobile du baromètre est tout cassé 

### ISSUE THREAD

**Issue by BenoitLeveque** [afup/barometre#182]
Il y a un problème au niveau de la couleur des liens du menu.

![img_0323](https://cloud.githubusercontent.com/assets/242870/6040444/2fbc9330-ac72-11e4-8c40-eab8d505343f.PNG)

**Comment by agallou** [comment]
Un git bisect m'indique que le problème vient du commit df001afbf3f262e928470121dc3d272ec9e8290c
Je regarde pour corriger ça.

**Comment by BenoitLeveque** [comment]
:( c'est moi en plus qui l'ai fais
