### ISSUE TITLE
Questionnaire 2015 ne contient pas les framework proprio

### ISSUE THREAD

**Issue by Guillaume-Rossignol** [afup/barometre#186]
Le formulaire 2015 à l'adresse https://docs.google.com/a/wizacha.com/forms/d/1PEK-uCpyH4ay48Bco91TD1w7gt-VzbI0bHcEErNm-Hw/viewform?embedded=false ne contient pas dans la catégorie «votre plus grande spécialité» la catégorie framework propriétaire.

C'est certainement à rapprocher du bug #172 à propos des répartitions

**Comment by omansour** [comment]
en fait le 2013 et 2014 ne contenait pas ce groupement également. 

il faudrait avoir un dump de la bdd de prod pour investiguer. je vais demander ça

**Comment by BenoitLeveque** [comment]
je peux créer ce dump si tu en as besoin

**Comment by omansour** [comment]
je veux bien. tu me le passe sur mon mail ?

**Comment by omansour** [comment]
j'ai corrigé le questionnaire
