### ISSUE TITLE
[Salary] Erreur sur filtre Sexe, contenant "Non précisé"

### ISSUE THREAD

**Issue by borisschapira** [afup/barometre#197]
Sur http://barometre.afup.org/report/salary, si on choisit "Non précisé" dans le filtre "Sexe", erreur 500.
cf. https://twitter.com/borisschapira/status/584413689622745089

**Comment by omansour** [comment]
`An exception occurred while executing 'CREATE TEMPORARY TABLE `tmp_ee5055b03fb793da756a85cebb767f0d` SELECT response.id as response_id FROM response response WHERE response.gender IN () GROUP BY response_id':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY response_id' at line 1 `

**Comment by BenoitLeveque** [comment]
je suis entrain de faire la correction

**Comment by omansour** [comment]
ha cool :) car moi j'allais faire un Starcraft :)
