### ISSUE TITLE
Ajout d'un graphique représentant l'évolution des statuts

### ISSUE THREAD

**Issue by agallou** [afup/barometre#287]
Sur https://barometre.afup.org/report/status?filter%5Bcampaign%5D%5B0%5D=4
on peux voir les statuts, filtrés par année.

L'année dernière nous avons ajouté un grpahique permettant de visualiser la part des versions de PHP
https://barometre.afup.org/report/php_version?filter%5Bcampaign%5D%5B0%5D=4

Il serait utile de d'avoir le même type de graphique sur la page statut.

**Comment by klnjmm** [comment]
Ok, je prends.
