### ISSUE TITLE
Ajout d'un graphique représentant l'évolution du télétravail

### ISSUE THREAD

**Issue by agallou** [afup/barometre#288]
Sur https://barometre.afup.org/report/remote_usage?filter%5Bcampaign%5D%5B0%5D=4 on peux voir l'état du télétravail, filtré par année.

L'année dernière nous avons ajouté un grpahique permettant de visualiser la part des versions de PHP
https://barometre.afup.org/report/php_version?filter%5Bcampaign%5D%5B0%5D=4

Il serait utile de d'avoir le même type de graphique sur la page télétravail.

**Comment by klnjmm** [comment]
Je prends aussi
