### ISSUE TITLE
Ajout d'article sur la partie revue de presse

### ISSUE THREAD

**Issue by agallou** [afup/barometre#296]
Le JDN a publié un article à propos du baromètre 2017 : 
https://www.journaldunet.com/management/salaire-cadres/1208691-les-salaires-des-dev-php-explosent-en-2017/

Il serait utile de le rajouter sur la page revue de presse : https://barometre.afup.org/press_review

(on pourrait aussi ajouter celui d'annonce des résultats sur afup.org : https://afup.org/news/994-decouvrez-les-resultats-du-barometre-des-salaires)

**Comment by klnjmm** [comment]
Il y a celui là aussi non : https://www.toolinux.com/?Mise-a-jour-du-barometre-des-salaires-PHP ?

**Comment by agallou** [comment]
oui, on peux aussi l'y ajouter
