### ISSUE TITLE
Ajouter l'information sur le type de contrat / heures travaillés

### ISSUE THREAD

**Issue by agallou** [afup/barometre#303]
Il pourrait être information d'avoir le nombre d'heures travaillées par semaine. Le type de contrat (forfait jour / 39h / 35h/ autre), ainsi que s'il y a des RTT (les questions et propositions seront à travailler).

**Comment by klnjmm** [comment]
Comment procède-t-on pour cette issue ? On définit ensemble ici les questions et réponses possibles ?

**Comment by klnjmm** [comment]
Au final, ça n'a pas été inclut dans le questionnaire 2019 si je ne me trompes pas ?

**Comment by klnjmm** [comment]
Fix in https://github.com/afup/barometre/pull/328
