### ISSUE TITLE
Type d'entreprise : ajouter agence web

### ISSUE THREAD

**Issue by agallou** [afup/barometre#307]
Dans la prochaine enquête, ajouter agence web dans les types d'entreprises que l'on peux choisir.

**Comment by klnjmm** [comment]
Pour cette issue, je vois qu'il y a déjà ça dans le fichier `CompanyTypeEnums` : 
```
self::SSII         => "SSII / agence web / conseil",
```

Est-ce suffisant ?

**Comment by BenoitLeveque** [comment]
je pense qu'il faudrait ajouter un nouveaux champs dans le questionnaire
