### ISSUE TITLE
Inclure une option non-binaire pour le genre

### ISSUE THREAD

**Issue by Mx-Glitter** [afup/barometre#311]

**Comment by agallou** [comment]
Merci pour la suggestion. Nous notons de rajouter l'option pour l'enquête 2019.

**Comment by klnjmm** [comment]
Je comprends pas trop ce qu'il faut rajouter là.
Actuellement il y a ça : 

```
        self::MALE => 'Hommes',
        self::FEMALE => 'Femmes',
        self::NONE => 'Non précisé',
```

**Comment by Mx-Glitter** [comment]
@klnjmm

"Non précisé" veut dire qu'on ne veut pas répondre, "non-binaire" est une autre option que "homme" ou "femme". Du coup je préconise l'option suivante pour parler des groupes de personnes :

```php
[
    self::MALE       => 'Hommes',
    self::FEMALE     => 'Femmes',
    self::NON_BINARY => 'Personnes non-binaires',
    self::NONE       => 'Non précisé',
]
```

Et dans le questionnaire pour choisir son genre quelque chose comme "Je suis :"

- [ ] Un homme
- [ ] Une femme
- [ ] Une personne non-binaire
- [ ] Je préfère ne pas répondre

**Comment by metalmumu** [comment]
A-t-on vraiment besoin de demander le genre?
Ne peut on pas simplement enlever ce champ?

**Comment by Guillaume-Rossignol** [comment]
Ça me semble pertinnent de le garder pour pouvoir identifier s'il y a des écarts qui ne sont que en fonction du genre.

Après, sur la question de ce qu'on laisse répondre à cette question, mon avis et de mettre toutes les options qui sont désirées et on géra par la suite si certaines réponses ne sont jamais choisies

**Comment by Mx-Glitter** [comment]
@metalmumu Si l'option est présente, c'est précisément pour faire des statistiques sur la diversité des personnes de la tech en PHP. Voici un équivalent fait par GitHub : https://github.com/about/diversity pour avoir une idée de ce qu'on cherche à obtenir. Si on ne veut pas faire de statistiques dessus, effectivement, il vaut mieux ne pas mettre la question.

À titre personnel, je trouve ça intéressant de faire ce travail d'introspection sur notre communauté pour se rendre compte de notre niveau d'inclusion des différentes populations qui subissent des oppressions systémiques.
