### ISSUE TITLE
Revoir wording champ acception communication

### ISSUE THREAD

**Issue by agallou** [afup/barometre#313]
A la fin de l'enquête on demande : "Je souhaite être averti(e) des prochaines enquêtes du baromètre".

Avec ce wording on ne peux pas contacter les participants et participantes pour les prévenir des résultats, une fois qu'ils sont publiés.

C'est dommage, vu que ça pourrait les intéresser. Pour l'enquête 2019 il faudra modifier ça.

**Comment by BenoitLeveque** [comment]
j'ai modifié le wording par celui proposé lors de la dernière réunion
