### ISSUE TITLE
Ajout d'articles dans la section revue de presse

### ISSUE THREAD

**Issue by agallou** [afup/barometre#315]
sur la page https://barometre.afup.org/press_review il faudrait ajouter de nouveaux articles :

* 2019
  * https://www.toolinux.com/?barometre-salaires-php-2018
  * https://www.journaldunet.com/solutions/dsi/1420610-php-la-progression-des-salaires-se-tasse-en-2018/
  * https://afup.org/news/1026-resultats-du-barometre-php-2018-publies
* 2018 
  * https://afup.org/news/1008-nouvelle-edition-du-barometre-des-salaires-php-en-collaboration-avec-le-jdn
  * https://www.journaldunet.com/web-tech/developpeur/1211460-le-barometre-des-salaires-php-c-est-parti-pour-2018/

**Comment by klnjmm** [comment]
Je prends

**Comment by agallou** [comment]
@BenoitLeveque a commencé à traiter cela : https://github.com/afup/barometre/pull/316

**Comment by klnjmm** [comment]
oui j'ai vu après en allant parcourir les PRs. Je me désassigne.

**Comment by BenoitLeveque** [comment]
mergé et deployé le 15 juillet
