### ISSUE TITLE
Ajout de question sur la documentation de PHP

### ISSUE THREAD

**Issue by macintoshplus** [afup/barometre#317]
Si vous avez besoin d'information sur une fonctionnalité en PHP vous utilisez :
- La documentation de PHP.net en français
- La documentation de PHP.net en anglais
- La documentation de PHP.net en français puis en anglais si elle est incomplète/incompréhensible
- Autre (documentation intégré dans un IDE par exemple)

Vous trouvez que la qualité de la documentation française de PHP est :
- Très bonne
- Bonne
- Acceptable
- Mauvaise
- Très mauvaise

**Comment by klnjmm** [comment]
J'ai un peu de mal à voir la pertinence de cette issue par rapport au baromètre des salaires. Qu'est-ce que cela va apporter aux personnes qui vont consulter le site ?

Dans le cadre du sondage, est-ce que ça apportera vraiment quelque chose de savoir que 70% des gens trouve la documentation `Très Bonne` et qu'il consulte majoritairement la documentation en anglais ?

**Comment by klnjmm** [comment]
Il y a d'ailleurs dans le code un même genre de réponse possible par rapport à l'attrait de PHP. (src/Afup/BarometreBundle/Enums/PHPStrengthEnums.php)
```
    protected $choices = array(
        self::ECOSYSTEME           => "Son écosystème (outils, frameworks, documentation)",
        self::NOMBRE_UTILISATEUR   => "Le nombre de développeurs et de sociétés l'utilisant",
        self::QUALITE_DEVELOPPEUR  => "La qualité des développeurs sur le marché",
        self::PERFORMANCE          => "Sa performance",
        self::FACILITE_UTILISATION => "Sa facilité d'utilisation",
    );
```

Et sauf erreur, je ne retrouve pas de page sur le site web qui affiche ces données.

**Comment by macintoshplus** [comment]
Le but est d'avoir un retour sur l'utilisation et la qualité de la doc PHP. Il est très difficile d'en avoir et pourtant tout le monde a besoin de la doc.

La documentation du langage PHP fait partie de son écosystème. Les questions donneront un premier aperçu de la façon dont les dev accèdent à la doc et leur ressenti envers elle.
Le but est de voir l'évolution dans le temps.

**Comment by klnjmm** [comment]
Je comprends l’objectif de cette question pour avoir un retour sur la doc. Je disais juste que je ne vois pas ce que ça va apporter aux personnes qui vont répondre aux sondages (comme ce que je mettais au dessus sur les qualités du PHP).

**Comment by macintoshplus** [comment]
Pour répondre à ta question avec beaucoup de retard (désolé), ça mettra peut être en évidence une utilisation accrue de la doc d'en une langue par rapport à un autre.

Du coup, les questions seront elles présentes au prochain baromètre ?

**Comment by BenoitLeveque** [comment]
Oui elle seront présente dans la prochaine campagne du barometre (qui commence demain)

**Comment by macintoshplus** [comment]
Merci @BenoitLeveque , j'ai hâte d'y répondre !

**Comment by klnjmm** [comment]
Fix in https://github.com/afup/barometre/pull/328
